name: Documentation to github wiki
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Get Latest Release
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        id: latest_release
        with:
          repository: ${{ env.GITHUB_REPOSITORY }}
          excludes: prerelease, draft
      - run: npm ci
      - name: Build Wiki
        run: npm run build:doc
      - name: Publish to GitHub Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "doc"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          WIKI_COMMIT_MESSAGE: ${{ steps.latest_release.outputs.release }}
